// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VySPA.Db;

namespace VySPA.Migrations
{
    [DbContext(typeof(FaQDbContext))]
    [Migration("20191113122144_FaQMigration")]
    partial class FaQMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VySPA.Models.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnswerText");

                    b.Property<string>("QuestionText");

                    b.Property<int>("Rating");

                    b.HasKey("Id");

                    b.ToTable("Question");

                    b.HasData(
                        new { Id = 1, AnswerText = "With a travel payment card you can travel within the Oslo and Akershus region on Vy and Ruter transportation using “refillable” electronic tickets. Vy and Ruter cooperate on the electronic travel payment card system.", QuestionText = "What is a travel payment card?", Rating = 0 },
                        new { Id = 2, AnswerText = "Tickets are released for sale 90 days before departure. There may be shorter sales periods if there is planned work on the train’s route or in connection with route changes in June and December.", QuestionText = "How long ahead of departure can I purchase a train ticket?", Rating = 0 },
                        new { Id = 3, AnswerText = "Our trains have a pet-free zone where animals are not permitted. On trains with seat reservations you can reserve a seat in a pet - free zone; on trains without seat reservations you will find a car displaying the “pet - free” symbol.", QuestionText = "Do you have a pet-free zone for allergy sufferers?", Rating = 0 },
                        new { Id = 4, AnswerText = "The easiest way to retrieve tickets purchased online at vy.no is through the Vy app. Tickets may also be downloaded as a PDF or retrieved on board the train or at a ticket vending machine, a staffed station, or select Narvesen convenience-store kiosks.", QuestionText = "How do I retrieve tickets purchased via vy.no?", Rating = 0 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
